spring:
  application:
    name: microservice-server-zuul
  profiles:
    active: 8760

hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: true
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true

# 根据以下实例配置动态路由规则
zuul:
  exclude:
    urls: /user/toLogin,/swagger-ui,.js,.css,.png,/swagger-resources,/api-docs
  max:
    host:
      connections: 500
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

