security:
  basic:
    enabled: true   #添加eureka的登录认证
  user:
    name: user
    password: password123
server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false 
    eviction-interval-timer-in-ms: 4000
    
  client:
    register-with-eureka: false   #把erueka的注册中心不开启认证和注册
    fetch-registry: false    #表明要不要从eureka服务器端拉取数据
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka  #此种形式的认证为linux的系统下的curl Style 认证方式